<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>true</IsPackable>

        <Description>gRPC direct request/response transport for Raycynix messaging with logical operation routing, generated client integration, and configuration-based registration.</Description>
        <PackageTags>raycynix;messaging;grpc;direct-requests;request-response;protobuf;client;transport;configuration;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
        <None Include="$(MSBuildThisFileDirectory)CHANGELOG.md" Pack="false" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.Net.Client" Version="2.83.0"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Raycynix.Extensions.Messaging\Raycynix.Extensions.Messaging.csproj"/>
    </ItemGroup>

</Project>
