<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>

        <Version>1.0.0</Version>
    </PropertyGroup>

    <PropertyGroup>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Core" Version="1.62.0" />
        <PackageReference Include="coverlet.MTP" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="FluentAssertions" Version="8.11.0" />
        <PackageReference Include="Microsoft.ApplicationInsights" Version="3.1.2" />
        <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.0.12" />
        <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.12" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="OpenTelemetry" Version="1.18.0" />
        <PackageReference Include="System.Memory.Data" Version="10.0.12" />
        <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.1" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Raycynix.Extensions.Common\Raycynix.Extensions.Common.csproj" />
        <ProjectReference Include="..\..\src\Raycynix.Extensions.Exceptions\Raycynix.Extensions.Exceptions.csproj" />
        <ProjectReference Include="..\..\src\Raycynix.Extensions.Exceptions.Abstractions\Raycynix.Extensions.Exceptions.Abstractions.csproj" />
        <ProjectReference Include="..\..\src\Raycynix.Extensions.Exceptions.AspNetCore\Raycynix.Extensions.Exceptions.AspNetCore.csproj" />
    </ItemGroup>

</Project>
