<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>

        <Version>1.0.0</Version>
    </PropertyGroup>


    <PropertyGroup>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.MTP" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="FluentAssertions" Version="8.11.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
        <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.1" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Raycynix.Extensions.Email\Raycynix.Extensions.Email.csproj" />
        <ProjectReference Include="..\..\src\Raycynix.Extensions.Email.Abstractions\Raycynix.Extensions.Email.Abstractions.csproj" />
        <ProjectReference Include="..\..\src\Raycynix.Extensions.Email.Smtp\Raycynix.Extensions.Email.Smtp.csproj" />
    </ItemGroup>

</Project>
