<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>true</IsPackable>

        <Description>RabbitMQ transport integration for Raycynix messaging with topology bootstrap, inbound consumer hosting, retry/dead-letter handling, and configuration-based setup.</Description>
        <PackageTags>raycynix;messaging;rabbitmq;amqp;events;consumer;topology;retry;dead-letter;configuration;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
        <None Include="$(MSBuildThisFileDirectory)CHANGELOG.md" Pack="false" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="RabbitMQ.Client" Version="7.2.2"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
        <PackageReference Include="System.Threading.RateLimiting" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Raycynix.Extensions.Messaging\Raycynix.Extensions.Messaging.csproj"/>
    </ItemGroup>

</Project>
