<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    </PropertyGroup>

    <PropertyGroup>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Raycynix.Extensions.Contracts\Raycynix.Extensions.Contracts.csproj" />
      <ProjectReference Include="..\..\src\Raycynix.Extensions.Contracts.AspNetCore\Raycynix.Extensions.Contracts.AspNetCore.csproj" />
    </ItemGroup>

</Project>
