<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>true</IsPackable>

        <Description>ASP.NET Core integration for Raycynix contracts, with validated endpoint metadata, request and response contract headers, MVC attributes, Minimal API helpers, versioned results, and ModelState error conversion.</Description>
        <PackageTags>raycynix;contracts;aspnetcore;minimal-api;mvc;headers;contract-versioning;contract-metadata;http;middleware;results;validation;dotnet;net10</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
        <None Include="$(MSBuildThisFileDirectory)CHANGELOG.md" Pack="false" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Raycynix.Extensions.Contracts\Raycynix.Extensions.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
