<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    </PropertyGroup>

    <PropertyGroup>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Raycynix.Extensions.Database.AspNetCore.Identity\Raycynix.Extensions.Database.AspNetCore.Identity.csproj" />
        <ProjectReference Include="..\..\src\Raycynix.Extensions.Database.AspNetCore\Raycynix.Extensions.Database.AspNetCore.csproj" />
        <ProjectReference Include="..\..\src\Raycynix.Extensions.Database.Sqlite\Raycynix.Extensions.Database.Sqlite.csproj" />
        <ProjectReference Include="..\..\src\Raycynix.Extensions.Database\Raycynix.Extensions.Database.csproj" />
        <ProjectReference Include="..\..\src\Raycynix.Extensions.Serilog\Raycynix.Extensions.Serilog.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="appsettings.Development.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    
</Project>
