<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>true</IsPackable>
        
        <Description>Shared infrastructure primitives and helpers for Raycynix applications, including operation context, assembly metadata helpers, and reusable disposable utilities.</Description>
        <PackageTags>raycynix;common;shared;helpers;context;correlation;assembly;disposable;infrastructure;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
        <None Include="$(MSBuildThisFileDirectory)CHANGELOG.md" Pack="false" Visible="false" PackagePath="\"/>
    </ItemGroup>

</Project>
