<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>true</IsPackable>

        <Description>Kafka transport integration for Raycynix messaging with publisher registration, inbound consumer hosting, retry/dead-letter support, and configuration-based setup.</Description>
        <PackageTags>raycynix;messaging;kafka;events;producer;consumer;retry;dead-letter;configuration;dotnet</PackageTags>

        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" Visible="false" PackagePath="\"/>
        <None Include="$(MSBuildThisFileDirectory)CHANGELOG.md" Pack="false" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Confluent.Kafka" Version="2.15.1" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Raycynix.Extensions.Messaging\Raycynix.Extensions.Messaging.csproj"/>
    </ItemGroup>

</Project>
